# My Key
spring.profiles.include=API-KEY

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG

# API Keys with Environment Variable support
data-key=${DATA_GO_KR_API_KEY:bXOBpAlAWob6rn15J58WyUhjpy+uQp1lexYuWvI3BSdjNnXwcHQXpkwLI0SWqS9nwSXdqk4V2JrcZ+0HcMcGbw==}
kakao-api-key=${KAKAO_API_KEY:b7ec6a8ef6864fb3ceddf316fa49c2b5}
